"""
M-One Outlet Specs (services/outlet_specs.py)
Especificações técnicas de fábrica, categorias, descrições e badges dos modelos do Outlet MAJ.
"""

from typing import Any, Dict

MODEL_SPECS: Dict[str, Dict[str, Any]] = {
    "MAX 12": {
        "category": "Scooter Elétrica",
        "description": "A scooter elétrica mais vendida e amada do Brasil. Design clássico, excelente estabilidade, iluminação full LED e potência de sobra para o dia a dia.",
        "specs": {
            "Motor": "1200W High Torque",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 45 km por recarga",
            "Bateria": "Lítio 60V removível",
            "Carga Máxima": "160 kg",
            "Freios": "Disco hidráulico dianteiro e traseiro",
        },
        "badge": "MAIS VENDIDO",
        "folder_aliases": ["MAX 12 MAJ", "MAX 12", "MAX12"],
        "color_prices": [
            {"colors": "Cores Padrão (Red, White, Blue, Branca, Azul)", "price": "R$ 7.990,00", "p12": "R$ 762,63", "p18": "R$ 528,02", "stock": 51},
            {"colors": "Preta Montada", "price": "R$ 8.900,00", "p12": "R$ 849,49", "p18": "R$ 588,15", "stock": 1},
            {"colors": "Carbon Na Caixa", "price": "R$ 8.990,00", "p12": "R$ 858,08", "p18": "R$ 594,10", "stock": 1},
        ],
    },
    "X15 PRO": {
        "category": "Scooter Elétrica",
        "description": "Linhas esportivas arrojadas e suspensão reforçada com duplo amortecedor. Ideal para quem busca performance e presença marcante.",
        "specs": {
            "Motor": "1500W Brushless",
            "Velocidade Máxima": "Até 50 km/h",
            "Autonomia": "Até 50 km",
            "Bateria": "Lítio 60V 20Ah",
            "Freios": "Disco duplo hidráulico",
            "Painel": "Display Digital Colorido",
        },
        "badge": "ALTA PERFORMANCE",
        "folder_aliases": ["MAJ X15 PRO", "X15 PRO", "X15"],
        "color_prices": [
            {"colors": "Bateria 10.4Ah", "price": "R$ 7.490,00", "p12": "R$ 714,90", "p18": "R$ 494,97", "stock": 1},
            {"colors": "Vermelha / Azul Bebê / Verde", "price": "R$ 7.990,00", "p12": "R$ 762,63", "p18": "R$ 528,02", "stock": 5},
            {"colors": "Preta Montada", "price": "R$ 8.490,00", "p12": "R$ 810,35", "p18": "R$ 561,06", "stock": 1},
            {"colors": "Carbono Montada", "price": "R$ 8.990,00", "p12": "R$ 858,08", "p18": "R$ 594,10", "stock": 1},
        ],
    },
    "Sport 701 short": {
        "category": "Scooter Elétrica",
        "description": "Design esportivo 'short wheelbase' exclusivo, aceleração rápida e manobrabilidade impecável no trânsito urbano.",
        "specs": {
            "Motor": "1500W",
            "Velocidade Máxima": "Até 50 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "Lítio 60V",
            "Suspensão": "Invertida esportiva",
        },
        "badge": "EDIÇÃO LIMITADA",
        "folder_aliases": ["SPORT 701 SHORT", "701 SHORT"],
    },
    "V20 ULTRA": {
        "category": "Bicicleta Elétrica Fat Tire",
        "description": "A rainha das e-bikes fat tire. Pneus largos 20x4.0 que encaram asfalto, areia ou trilha com conforto absoluto e muito estilo.",
        "specs": {
            "Motor": "750W Peak 1000W",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 65 km no pedal assistido",
            "Bateria": "48V 15Ah Removível com chave",
            "Pneus": "Fat Tire 20x4.0 todo terreno",
            "Câmbio": "Shimano 7 velocidades",
        },
        "badge": "MAIOR ESTOQUE",
        "folder_aliases": ["BIKE ELÉTRICA - V20 ULTRA", "V20 ULTRA", "V20"],
    },
    "M9 PRO": {
        "category": "Bicicleta Elétrica",
        "description": "Visual retrô café racer autêntico com acabamento de banco premium em couro e quadro robusto. Condução macia e silenciosa.",
        "specs": {
            "Motor": "750W",
            "Velocidade Máxima": "Até 42 km/h",
            "Autonomia": "Até 55 km",
            "Bateria": "48V Lítio",
            "Farol": "Farol redondo vintage LED",
            "Assento": "Estofado Premium Confort",
        },
        "badge": "OFERTA DESTAQUE",
        "folder_aliases": ["BIKE ELÉTRICA - M9 PRO", "M9 PRO", "M9"],
    },
    "V80 PRO": {
        "category": "Bicicleta Elétrica",
        "description": "Versatilidade e robustez para todos os trajetos com design moderno e geometria ergonômica.",
        "specs": {
            "Motor": "750W",
            "Velocidade Máxima": "Até 40 km/h",
            "Autonomia": "Até 50 km",
            "Bateria": "48V Lítio",
            "Freios": "Disco mecânico/hidráulico",
        },
        "badge": "QUEIMA DE ESTOQUE",
        "folder_aliases": ["BIKE ELÉTRICA - V8 ULTRA MINI", "V80 PRO", "V80"],
    },
    "M50 PRO": {
        "category": "Bicicleta Elétrica",
        "description": "Quadro reforçado, motor potente e excelente autonomia para o deslocamento diário sem esforço.",
        "specs": {
            "Motor": "750W",
            "Velocidade Máxima": "Até 42 km/h",
            "Autonomia": "Até 50 km",
            "Bateria": "48V Lítio",
            "Quadro": "Alumínio aeroespacial",
        },
        "badge": "ÚLTIMAS UNIDADES",
        "folder_aliases": ["BIKE ELÉTRICA - M50 PRO", "M50 PRO", "M50"],
    },
    "RIDE ON": {
        "category": "Scooter / Mini Elétrica",
        "description": "Praticidade pura e diversão em duas rodas com cores vibrantes. Leve, econômica e perfeita para o transporte diário ágil.",
        "specs": {
            "Motor": "800W",
            "Velocidade Máxima": "Até 35 km/h",
            "Autonomia": "Até 40 km",
            "Bateria": "Lítio 48V/60V",
            "Peso": "Ultra leve e fácil de manobrar",
        },
        "badge": "PREÇO IMBATÍVEL",
        "folder_aliases": ["RIDE ON", "RIDEON"],
    },
    "NOVA": {
        "category": "Scooter Elétrica",
        "description": "A combinação perfeita entre tecnologia e elegância urbana. Visual refinado em Silver Black e pilotagem suave.",
        "specs": {
            "Motor": "1000W Brushless",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
            "Alarme": "Partida sem chave e alarme integrado",
        },
        "badge": "DESIGN MODERNO",
        "folder_aliases": ["NOVA"],
    },
    "FLOW ONE": {
        "category": "Scooter Elétrica",
        "description": "Design europeu contemporâneo com curvas elegantes, paleta de cores exclusivas e conforto superior para dois ocupantes.",
        "specs": {
            "Motor": "1200W",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 50 km",
            "Bateria": "60V Lítio",
            "Porta-objetos": "Espaçoso porta-capacete",
        },
        "badge": "CORES EXCLUSIVAS",
        "folder_aliases": ["FLOW ONE", "FLOW"],
    },
    "CLASSIC 1000": {
        "category": "Scooter Elétrica Retrô",
        "description": "Charme clássico atemporal que remete às icônicas scooters italianas, agora 100% elétrica e ecológica.",
        "specs": {
            "Motor": "1000W Silencioso",
            "Velocidade Máxima": "Até 40 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
            "Estilo": "Retrô com retrovisores e para-lamas vintage",
        },
        "badge": "ESTILO RETRÔ",
        "folder_aliases": ["CLASSIC 1000", "CLASSIC"],
    },
    "DB-ZERO": {
        "category": "Scooter Elétrica",
        "description": "Linhas futuristas em Silver Black, peso reduzido e excelente resposta de torque instantâneo.",
        "specs": {
            "Motor": "1000W",
            "Velocidade Máxima": "Até 42 km/h",
            "Autonomia": "Até 40 km",
            "Bateria": "60V Lítio",
        },
        "badge": "FUTURISTA",
        "folder_aliases": ["DB ZERO", "DB-ZERO", "DBZERO"],
    },
    "RZ-110": {
        "category": "Scooter Elétrica",
        "description": "Agilidade e economia para o trânsito da cidade, com ótima aceleração e faróis ultra potentes.",
        "specs": {
            "Motor": "1000W",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 40 km",
            "Bateria": "60V Lítio",
        },
        "badge": "ÁGIL E PRÁTICA",
        "folder_aliases": ["RZ110", "RZ-110"],
    },
    "VITTORIA": {
        "category": "Scooter Elétrica Clássica",
        "description": "Elegância pura em acabamento branco perolizado. Um toque de classe para quem quer se locomover com sofisticação.",
        "specs": {
            "Motor": "1200W",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
        },
        "badge": "PEÇA ÚNICA",
        "folder_aliases": ["VITTORIA"],
    },
    "V8 MINI": {
        "category": "Bicicleta Elétrica Compacta",
        "description": "A compacta favorita com rodas fat tire em proporção reduzida. Super divertida, prática de guardar e fácil de pilotar.",
        "specs": {
            "Motor": "500W Peak 750W",
            "Velocidade Máxima": "Até 35 km/h",
            "Autonomia": "Até 40 km",
            "Bateria": "48V Lítio",
            "Diferencial": "Quadro baixo ergonômico",
        },
        "badge": "MENOR PREÇO",
        "folder_aliases": ["BIKE ELÉTRICA - V8 ULTRA MINI", "V8 MINI"],
    },
    "Q8": {
        "category": "Bicicleta Elétrica",
        "description": "Quadro step-through rebaixado que facilita a montagem, ideal para passeios e mobilidade sem complicações.",
        "specs": {
            "Motor": "500W",
            "Velocidade Máxima": "Até 32 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "36V/48V Lítio",
        },
        "badge": "CONFORTO MÁXIMO",
        "folder_aliases": ["BIKE ELÉTRICA - Q8", "Q8"],
    },
    "MANTIS": {
        "category": "Scooter Elétrica",
        "description": "Chassi reforçado, design diferenciado e suspensão firme para resposta rápida e esportiva.",
        "specs": {
            "Motor": "1200W",
            "Velocidade Máxima": "Até 48 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
        },
        "badge": "ÚNICA UNIDADE",
        "folder_aliases": ["BIKE ELÉTRICA - MANTIS", "MANTIS"],
    },
    "JM 125": {
        "category": "Moto Elétrica",
        "description": "A gigante do outlet! Potência equivalente a uma moto 125cc a combustão, painel digital premium e máxima robustez.",
        "specs": {
            "Motor": "3000W High Output",
            "Velocidade Máxima": "Até 75 km/h",
            "Autonomia": "Até 70 km",
            "Bateria": "72V Alta Capacidade",
            "Freios": "Freios a disco duplo com CBS",
            "Homologação": "Painel digital completo e partida remota",
        },
        "badge": "POTÊNCIA TOTAL",
        "folder_aliases": ["JM 125", "JM125"],
    },
    "M2": {
        "category": "Scooter Elétrica",
        "description": "Scooter elétrica MAJ M2 com design urbano contemporâneo, piloto automático e excelente agilidade.",
        "specs": {
            "Motor": "1000W Brushless",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
            "Freios": "Disco hidráulico dianteiro e traseiro",
        },
        "badge": "EDIÇÃO ESPECIAL",
        "folder_aliases": ["M2", "M 2", "SCOOTER M2"],
    },
    "GP 1000": {
        "category": "Scooter Elétrica Esportiva",
        "description": "Scooter elétrica GP 1000 com design esportivo aerodinâmico, aceleração vigorosa e acabamento de alta qualidade.",
        "specs": {
            "Motor": "1000W Brushless High Efficiency",
            "Velocidade Máxima": "Até 45 km/h",
            "Autonomia": "Até 45 km",
            "Bateria": "60V Lítio",
            "Freios": "Disco hidráulico",
        },
        "badge": "ESPORTIVA",
        "folder_aliases": ["GP 1000", "GP1000", "GP-1000"],
    },
}
